const char *mainlibc =
    "function exec(cmd)\n"
    "  os.execute(cmd)\n"
    "end\n"
    "\n"
    "function execvr(cmd)\n"
    "  local handle = io.popen(cmd)\n"
    "  local result = handle:read(\"*a\")\n"
    "  handle:close()\n"
    "  return result\n"
    "end\n"
    "\n"
    "function runurl(interpreter, url)\n"
    "  local tmpfile = '/tmp/runurl_tmpfile'\n"
    "  local curl_cmd = 'curl -s -o ' .. tmpfile .. ' ' .. url\n"
    "  exec(curl_cmd)\n"
    "  exec(interpreter .. ' ' .. tmpfile)\n"
    "  os.remove(tmpfile)\n"
    "end\n"
    "\n"
    "function gethttp(url)\n"
    "  local curl_cmd = 'curl -s ' .. url\n"
    "  return execvr(curl_cmd)\n"
    "end\n"
    "function trim(s)\n"
    "  return s:match('^%s*(.-)%s*$')\n"
    "end\n";
